version: '3.8'

services:
    db-1:
        container_name: ${APP_NAME}-db-1
        image: postgres:${POSTGRESQL_IMAGE_TAG}
        ports:
            - 15432:5432
        environment:
            TZ: "UTC"
            LANG: ja_JP.UTF-8
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
            POSTGRES_HOST_AUTH_METHOD: trust
    db-2:
        container_name: ${APP_NAME}-db-2
        image: postgres:${POSTGRESQL_IMAGE_TAG}
        ports:
            - 25432:5432
        environment:
            TZ: "UTC"
            LANG: ja_JP.UTF-8
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
            POSTGRES_HOST_AUTH_METHOD: trust
